### ISSUE TITLE
how to reset editor content

### ISSUE THREAD

**Issue by ghost** [myeongjae-kim/tui.editor-with-nextjs#3]
hi

in this file : https://github.com/myeongjae-kim/tui.editor-with-nextjs/blob/master/pages/index.tsx

how to reset editor content

thank you very much

**Comment by myeongjae-kim** [comment]
The editor has reset api, so you can reset editor contents by calling it. To call the reset api, you should do something in WysiwygEditor.tsx because it has a ref to the editor.

Of course you can modify editor's contents at index.tsx in some manner, but it's not recommended because what you are trying to do is accessing and modifying a child component's state at the parent. It isn't natural for React.

Here is a simple example: https://github.com/myeongjae-kim/tui.editor-with-nextjs/commit/bd0e6c2803cd7d265971404b5ad3d3680d2ca686

**Comment by ghost** [comment]
thank you very much
